server:
  port: 8888

registry:
  host: 127.0.0.1   # 微服务配置的地址（nacos配置中心，rabbitMQ等）

project:
  deployment:
    host: localhost

spring:
  datasource:
    url: jdbc:mysql:///negotiation?serverTimeZone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: file-service
  cloud:
    nacos:
      server-addr: ${registry.host}:8848
  rabbitmq:
    host: ${registry.host} # rabbitMQ的ip地址
    port: 5672 # 端口
    username: root
    password: admin
    virtual-host: /
  servlet:
    multipart:
      enabled: true     # 开启multipart的配置
      max-file-size: 100MB      # 单个文件的大小
      max-request-size: 100MB   # 总上传的数据大小
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0   # 逻辑删除

file:
  upload:
    relative-path: \localized-files\