server:
  port: 8082

universal:
  host: 43.142.14.211

spring:
  datasource:
    url: jdbc:mysql:///negotiation?serverTimeZone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: question-service
  cloud:
    nacos:
      server-addr: ${universal.host}:8848
  rabbitmq:
    host: ${universal.host} # rabbitMQ的ip地址
    port: 5672 # 端口
    username: root
    password: admin
    virtual-host: /
  servlet:
    multipart:
      enabled: true     # 开启multipart的配置
      max-file-size: 100MB      # 单个文件的大小
      max-request-size: 100MB   # 总上传的数据大小

mybatis-plus:
  global-config:
    db-config:
      logic-delete-value: 1
      logic-not-delete-value: 0   # 逻辑删除
